### ISSUE TITLE
Plugin does not work with my configuration

### ISSUE THREAD

**Issue by vittorio-c** [vimpostor/vim-lumen#10]
Hi,

Thank for this plugin !!

Unfortunately for me it does not work... When I change theme in Gnome from dark to light, nothing happens in nvim.

Could you help me debugging ?

I have no idea where to look.

Here is my configuration : 

```
❯ nvim --version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

         fichier vimrc système : "$VIM/sysinit.vim"
               $VIM par défaut : "/usr/share/nvim"

Run :checkhealth for more info
```

Gnome : 44.3

OS : Manjaro

Using X11

Linux 5.15.122-1

I have `gdbus` installed through Arch package [core/glib2](https://www.archlinux.org/packages/core/x86_64/glib2/) (installed version : `glib2-2.76.4-1`)

The output of `:echo lumen#debug#info()` is :  

```
{'platform': 'linux', 'job_state': 'run as PID 32164'}
```

For an other computer I have, this plugin works perfectly, with same `init.vim` file ! So I suppose it has something to do with some configuration Host wise ? 

I use "Night Theme Switcher" Gnome extension, with following settings : 

![link to image](https://ibb.co/SX3r1Vn)

<a href="https://ibb.co/SX3r1Vn"><img src="https://i.ibb.co/gMRVXtT/Capture-d-cran-du-2023-08-05-11-59-44.png" alt="Capture-d-cran-du-2023-08-05-11-59-44" border="0"></a>

In Gnome settings, I have these settings : 

![link to image](https://ibb.co/3SBdJzb)

<a href="https://ibb.co/3SBdJzb"><img src="https://i.ibb.co/vLZqtYW/Capture-d-cran-du-2023-08-05-12-03-26.png" alt="Capture-d-cran-du-2023-08-05-12-03-26" border="0"></a>

> Sorry if these two images are irrevelant to my problem, but I wanted to give max infos

The automatic theme switching between dark/light works in other applications like Firefox.

In nvim, I can `:set background=light/dark` manually on the fly, but not automatically wth this plugin.

Any idea ?

**Comment by vittorio-c** [comment]
Here is a minimalist `init.vim` with wich I can reproduce the bug : 

I removed all the plugins to make sure there was no interference.


```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'gruvbox-community/gruvbox'
Plug 'vimpostor/vim-lumen'
call plug#end()

runtime! debian.vim

" Syntax highligting
if has("syntax")
    syntax on
endif

" set color for tabs
:hi TabLineFill cterm=bold gui=bold

" enable true colors on terminal (if supported)
if exists('+termguicolors')
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    set termguicolors
endif

colorscheme gruvbox

" break lines at end of word
set linebreak

" jump to the lateste position when reopening a file
if has("autocmd")
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
    source /etc/vim/vimrc.local
endif


set cursorline          " cursor line highlight
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
set mouse=a		" Enable mouse usage (all modes)
set clipboard=unnamedplus
set number relativenumber
set backupcopy=yes
let mapleader = ","
let maplocalleader = ";"

" indent
" indent according to detected file
if has("autocmd")
    filetype plugin indent on
endif
"set autoindent
set smartindent

" tabs
set expandtab
set shiftwidth=4
set softtabstop=4

" tell vim where tag file is
" https://stackoverflow.com/a/58413644/10767428
set tags^=.git/tags;~


" ~~~~~~~~~~~~~~
" splits
" ~~~~~~~~~~~~~~
set splitbelow splitright
" Removes pipes | that act as separators on splits
set fillchars+=vert:\

" ~~~~~~~~~~~~~~
" autocompletion
" ~~~~~~~~~~~~~~
set omnifunc=syntaxcomplete#Complete

" controls how completions will appear.
set completeopt=noinsert,menuone,noselect

set pumheight=15

augroup vimrc_help
  autocmd!
  autocmd BufEnter *.txt if &buftype == 'help' | wincmd L | endif
augroup END

let g:python3_host_prog='/usr/bin/python3'

set autoread

" Triger `autoread` when files changes on disk
" https://unix.stackexchange.com/questions/149209/refresh-changed-content-of-file-opened-in-vim/383044#383044
" https://vi.stackexchange.com/questions/13692/prevent-focusgained-autocmd-running-in-command-line-editing-mode
    autocmd FocusGained,BufEnter,CursorHold,CursorHoldI *
            \ if mode() !~ '\v(c|r.?|!|t)' && getcmdwintype() == '' | checktime | endif

" Notification after file change
" https://vi.stackexchange.com/questions/13091/autocmd-event-for-autoread
autocmd FileChangedShellPost *
  \ echohl WarningMsg | echo "File changed on disk. Buffer reloaded." | echohl None
set exrc
set secure
set foldmethod=indent
set foldlevelstart=20
set conceallevel=2
```

**Comment by vimpostor** [comment]
What output do you get, when you run `gdbus monitor --session --dest org.freedesktop.portal.Desktop --object-path /org/freedesktop/portal/desktop` in a terminal and change the colorscheme?

On KDE I get something like this:
```
Monitoring signals on object /org/freedesktop/portal/desktop owned by org.freedesktop.portal.Desktop
The name org.freedesktop.portal.Desktop is owned by :1.5
/org/freedesktop/portal/desktop: org.freedesktop.portal.Settings.SettingChanged ('org.kde.kdeglobals.General', 'ColorScheme', <'BreezeLight'>)
/org/freedesktop/portal/desktop: org.freedesktop.portal.Settings.SettingChanged ('org.freedesktop.appearance', 'color-scheme', <uint32 2>)
/org/freedesktop/portal/desktop: org.freedesktop.portal.Settings.SettingChanged ('org.kde.kdeglobals.General', 'ColorScheme', <'BreezeDark'>)
/org/freedesktop/portal/desktop: org.freedesktop.portal.Settings.SettingChanged ('org.freedesktop.appearance', 'color-scheme', <uint32 1>)
```

**Comment by vittorio-c** [comment]
Thank you so much @vimpostor 

Thanks to your answer I could debug, and I needed to install `xdg-desktop-portal-gnome` and `xdg-desktop-portal-gtk`, because otherwise I had the message "_The name org.freedesktop.portal.Desktop does not have an owner_" when I ran the command you suggested (and no output when changin the theme).

Now everything works perfectly !
