### ISSUE TITLE
`List index out of range: 0` on `macOS-14` GitHub Actions runner

### ISSUE THREAD

**Issue by 5ouma** [vimpostor/vim-lumen#12]
### Describe the bug

I test my dotfiles on GitHub Actions and install vim-lumen via [tani/vim-jetpack](https://github.com/tani/vim-jetpack).
When it runs on a `macOS-14` runner, which is an M1 Mac, it outputs an error and stacks.
I'm not sure if this is due to GitHub Actions or Apple Silicon Mac, since I don't have an Apple Silicon Mac.

https://github.com/5ouma/dotfiles/actions/runs/7895428112/job/21547760528

### Debug output

```Text
Error detected while processing /Users/runner/.local/share/vim/pack/jetpack/opt/vim-lumen/plugin/lumen.vim[6]..function lumen#init[7]..lumen#oneshot[1]..lumen#platforms#call[10]..lumen#platforms#macos#oneshot:
line    4:
E684: List index out of range: 0
```

**Comment by vimpostor** [comment]
It should work now (I don't have a Mac to test though).
