### ISSUE TITLE
"Command terminated" when loading the plugin

### ISSUE THREAD

**Issue by kylegrieder** [vimpostor/vim-lumen#13]
### Describe the bug

Including the plugin in .vimrc causes "Command terminated\n\n Press ENTER or type command to continue" to display when launching vim. 

### To reproduce

![Screenshot 2024-04-15 at 02 46 41PM](https://github.com/vimpostor/vim-lumen/assets/25424229/96dee0f5-0bd7-4ad6-8fe1-54c77acdc3f0)

### Expected behavior

vim should just open

### Debug output

```Text
{'platform': 'macos', 'job_state': 'dead (exit code 122)', 'job_errors': [0, 0, 'executing job failed: No such file or directory']}
```

**Comment by vimpostor** [comment]
Did you follow the requirements in the README?

```
## MacOS
It is required that Swift is available on your system. Swift is shipped with Xcode for example.
```

If yes, what does `:echo lumen#platforms#macos#watch_cmd()` output and what happens if you copy the printed path, paste it into a terminal and run: `<copied-path> get`?

**Comment by kylegrieder** [comment]
> Did you follow the requirements in the README?

Yes. I have swift on my system.

`:echo lumen#platforms#macos#watch_cmd()` returns the path to `/vim-lumen/autoload/lumen/platforms/macos/watcher`. however when I paste that into a terminal followed by `get`, I receive the error: `zsh: no such file or directory`. Looking at that path, there is a `watcher.swift` file. when i change the cmd to be `/vim-lumen/autoload/lumen/platforms/macos/watcher.swift get` I get "Light" returned.

**Comment by kylegrieder** [comment]
I also tried removing the `.swift` extension and `chmod +x` to that file to make sure it is executable,  but I'm still getting the same issue.

**Comment by vimpostor** [comment]
Can you post the output when you run the following command in vim:
:echom systemlist(lumen#platforms#macos#watch_cmd()[0] . ".swift get")

**Comment by kylegrieder** [comment]
I get this: `['zsh:1: no such file or directory: /Users/kylegrieder/kyle.grieder']` which is likely referencing the fact that my `.vim` directory is symlinked to a directory with an absolute path that contains spaces.

**Comment by vimpostor** [comment]
> my `.vim` directory is symlinked to a directory with an absolute path that contains spaces.

Yup thanks for mentioning this, I forgot to escape the file path. It should work now.

**Comment by kylegrieder** [comment]
Just updated the plugin and can confirm it is now working. Thanks! 

Just to confirm, I can use the callbacks to set different color schemes for different modes right? i.e. - 

```
au User LumenLight colorscheme <light_color_scheme>
au User LumenDark colorscheme <dark_color_scheme>
```

**Comment by vimpostor** [comment]
> Just to confirm, I can use the callbacks to set different color schemes for different modes right? i.e. -
> 
> ```
> au User LumenLight colorscheme <light_color_scheme>
> au User LumenDark colorscheme <dark_color_scheme>
> ```

Yes, that should work.

**Comment by kylegrieder** [comment]
awesome, thanks! i appreciate your swift responses.

**Comment by vimpostor** [comment]
You can now also use the `g:lumen_dark_colorscheme` and `g:lumen_light_colorscheme` variables to achieve the same thing.
