### ISSUE TITLE
vim-lumen doesn't work without error messages in macOS

### ISSUE THREAD

**Issue by gmmyung** [vimpostor/vim-lumen#14]
### Describe the bug

After running Neovim, no error is observable. Toggling vim-lumen doesn't change the colorscheme.
It worked before, but it suddenly doesn't since I have updated the package.

### To reproduce

run Neovim

### Expected behavior

vim-lumen should work as expected

### Debug output

```Text
{'platform': 'macos', 'job_state': 'dead (exit code 257)', 'job_errors': []}
```

**Comment by vimpostor** [comment]
> but it suddenly doesn't since I have updated the package.

Which package did you update? If you mean this plugin, could you find out which commit broke it?

**Comment by gmmyung** [comment]
Unfortunately not. I haven't updated the package for a few months before this happened.

**Comment by gmmyung** [comment]
I have tried multiple versions, and 145a2fd seems to be where it starts to break.

**Comment by vimpostor** [comment]
What is the output of `:echom lumen#platforms#macos#watch_cmd()`?

**Comment by gmmyung** [comment]
/Users/gmmyung/.local/share/nvim/lazy/vim-lumen/autoload/lumen/platforms/macos/watcher

**Comment by gmmyung** [comment]
I am using [lazy.nvim](https://github.com/folke/lazy.nvim) for my package manager.

**Comment by vimpostor** [comment]
Hmm I do not see anything wrong with that path.

If you run `~/.local/share/nvim/lazy/vim-lumen/autoload/lumen/platforms/macos/watcher.swift get` in a shell, does it output something?
And if you run `~/.local/share/nvim/lazy/vim-lumen/autoload/lumen/platforms/macos/watcher`, does it output something when you change the system dark mode?

**Comment by gmmyung** [comment]
> If you run ~/.local/share/nvim/lazy/vim-lumen/autoload/lumen/platforms/macos/watcher.swift get in a shell, does it output something?
```
> ~/.local/share/nvim/lazy/vim-lumen/autoload/lumen/platforms/macos/watcher.swift get
Dark_
```
> And if you run ~/.local/share/nvim/lazy/vim-lumen/autoload/lumen/platforms/macos/watcher, does it output something when you change the system dark mode?
 ```
> ~/.local/share/nvim/lazy/vim-lumen/autoload/lumen/platforms/macos/watcher
Light
Dark_
```

**Comment by vimpostor** [comment]
Can you confirm that `:echom jobstart(["/Users/gmmyung/.local/share/nvim/lazy/vim-lumen/autoload/lumen/platforms/macos/watcher"])` outputs `-1`?

According to `:h jobstart()` this means that neovim thinks that this file is not executable.
Can you figure out why that would be the case, e.g. check that `chmod +x` is set on that file.

Also make sure that the path you posted for `:echom lumen#platforms#macos#watch_cmd()` really is that path and doesn't contain any hidden other characters, e.g. also try running `:echom jobstart(lumen#platforms#macos#watch_cmd())`.

**Comment by vimpostor** [comment]
I think I found the problem now, please kindly test the latest version.

**Comment by gmmyung** [comment]
> Can you confirm that `:echom jobstart(["/Users/gmmyung/.local/share/nvim/lazy/vim-lumen/autoload/lumen/platforms/macos/watcher"])` outputs -1?

This command outputs increasing number every time I enter. It increase more than 1 each time. I am at 43 now lol

> According to :h jobstart() this means that neovim thinks that this file is not executable.
Can you figure out why that would be the case, e.g. check that chmod +x is set on that file.

```
-rwxr-xr-x  1 gmmyung  staff  65416 Feb 11 18:23 /Users/gmmyung/.local/share/nvim/lazy/vim-lumen/autoload/lumen/platforms/macOS/watcher
```

`:echom jobstart(lumen#platforms#macos#watch_cmd())` outputs:
```
E475: Invalid value for argument cmd: ''/Users/gmmyung/.local/share/nvim/lazy/vim-lumen/autoload/lumen/platforms/macos/watcher'' is not executable
-1
Press ENTER or type command to continue
```
I will check if the fix works!

**Comment by gmmyung** [comment]
Works like a charm! Thank you for your swift response. I really appreciate it 👍
