### ISSUE TITLE
"Watcher is not executable" error and checkhealth deprecations 

### ISSUE THREAD

**Issue by melMass** [vimpostor/vim-lumen#15]
### Describe the bug

Hi,

Thanks for this but I'm unable to make it work, I have Xcode, command line tools, swift etc.

```sh
==============================================================================
lumen: require("lumen.health").check()

- WARNING vim.health.report_start() is deprecated, use vim.health.start() instead. :help |deprecated|
  Feature will be removed in Nvim 0.11

lumen report ~
- WARNING vim.health.report_ok() is deprecated, use vim.health.ok() instead. :help |deprecated|
  Feature will be removed in Nvim 0.11
- OK Platform macos is supported
- WARNING vim.health.report_error() is deprecated, use vim.health.error() instead. :help |deprecated|
  Feature will be removed in Nvim 0.11
- ERROR Background job is not running: dead (exit code 257)
- WARNING vim.health.report_warn() is deprecated, use vim.health.warn() instead. :help |deprecated|
  Feature will be removed in Nvim 0.11
- WARNING Job reported errors
  - ADVICE:
    - jobstart() failed: E475: Invalid value for argument cmd: '/Users/melmass/.local/share/nvim/lazy/vim-lumen/autoload/lumen/platforms/macos/watcher' is not executable
```

This is the result of `ls -ls` on the macOS folder:

```sh
name: watcher.swift
type: file
target: 
readonly: false
mode: rwxr-xr-x
num_links: 1
inode: 1106470
user: melmass
group: staff
size: 850 B
created: Tue, 11 Jun 2024 13:58:31 +0200 (32 minutes ago)
accessed: Tue, 11 Jun 2024 13:58:31 +0200 (32 minutes ago)
modified: Tue, 11 Jun 2024 13:58:31 +0200 (32 minutes ago)
```

### To reproduce

Install the plugin using lazy, this is what I have:

**plugins/ui.lua**

```lua
return {
   {
    'vimpostor/vim-lumen',
    dependencies = {
      'sainnhe/everforest',
      'vimpostor/vim-prism',
     },
    config = function(_, opts)
      -- require('lumen').setup({})
      vim.g.lumen_light_colorscheme = 'prism'
      vim.g.lumen_dark_colorscheme = 'catppuccin'
    end,
  },
```

### Expected behavior

-

### Debug output

```Text
{'platform': 'macos', 'job_state': 'dead (exit code 257)', 'job_errors': ['jobstart() failed: E475: Invalid value for argument cmd: ''/Us
ers/melmass/.local/share/nvim/lazy/vim-lumen/autoload/lumen/platforms/macos/watcher'' is not executable']}
```

**Comment by vimpostor** [comment]
What is the output if you run `:echom systemlist(printf("swiftc %s.swift -o /tmp/out", lumen#platforms#macos#watch_cmd()[0]))` in vim?

Does `:echom systemlist(printf("%s.swift get", lumen#platforms#macos#watch_cmd()[0]))` print something?

**Comment by melMass** [comment]
Thanks,

This: `:echom systemlist(printf("swiftc %s.swift -o /tmp/out", lumen#platforms#macos#watch_cmd()[0]))`

returns: `[]`

This: `:echom systemlist(printf("%s.swift get", lumen#platforms#macos#watch_cmd()[0]))`

returns: `['Dark_']` when in dark mode in macOS and `['Light']` when running in light mode (in the same session so that seem to work properly)

**Comment by vimpostor** [comment]
> This: `:echom systemlist(printf("swiftc %s.swift -o /tmp/out", lumen#platforms#macos#watch_cmd()[0]))`
> 
> returns: `[]`

It is weird that `swiftc` doesn't output any errors. Can you go to the `macos` directory of the plugin and run `swiftc watcher.swift -o watcher` manually in a shell?

Does it output anything or does it create the `watcher` binary?

**Comment by melMass** [comment]
That did it!
I'll know what to do if it rehappens on update, feel free to close this issue / ask me for further commands to run

**Comment by vimpostor** [comment]
Weird, usually the plugin should do that automatically on first startup. Do you use a non-standard shell?
Also would be interesting to get the output of: `:let a = lumen#platforms#macos#watch_cmd()[0] | echo systemlist(printf("%s get || swiftc %s.swift -o %s", a, a, a))`

**Comment by melMass** [comment]
Sorry for the late reply! 
Spot on, and I'm dumb I should have pointed it out, I do use a custom shell: nushell.
It does redirection and things like that completely differently (`vim.opt.shellredir = 'out+err> %s'`), so direct shell calls are probably the issue
