### ISSUE TITLE
Macos performance improvement suggestion

### ISSUE THREAD

**Issue by ghost** [vimpostor/vim-lumen#6]
I compiled the watcher.swift with `swiftc watcher.swift` and changed the `autoload/lumen/platforms/macos.vim` like this

```diff
-	return [s:path . "/macos/watcher.swift"]
+	return [s:path . "/macos/watcher"]
```

Startup time got 0.14 seconds shorter.

**Comment by vimpostor** [comment]
Are you using `let g:lumen_startup_overwrite = 1` by any chance? By default your change should not reduce startup time, because the only blocking call done is if you set that option.

I assume the startup time was measured with `--startuptime`? 140 milliseconds indeed is way too much.

**Comment by ghost** [comment]
Yes, I use `let g:lumen_startup_overwrite = 1`. Because when I open neovim, I want it to set the background properly.

- With `nvim --startuptime`, the improvement was `161.605 - 030.227 = 131.378` milliseconds for `plugin/lumen.vim`.
- With `time nvim +q`, the improvement was ~140 milliseconds.

**Comment by vimpostor** [comment]
OK thanks for the detailed measurements, this is absolutely something that has to be fixed, I didn't know that the Swift interpreter is **that** slow.
Would you mind measuring the total execution time of the compiled version? You can do that by compiling with `swiftc` as you already did and then running `time /path/to/vim-lumen/autoload/lumen/platforms/macos/watcher get`.
Hopefully the total execution time of the compiled version is low enough, then we can compile it on demand from the plugin. Otherwise we have to come up with another solution...

**Comment by ghost** [comment]
```
(           ./watcher get; )  0.01s user 0.01s system 52% cpu 0.024 total
(           ./watcher get; )  0.01s user 0.01s system 50% cpu 0.025 total
(           ./watcher get; )  0.01s user 0.01s system 58% cpu 0.033 total
(           ./watcher get; )  0.01s user 0.01s system 54% cpu 0.027 total

( swift watcher.swift get; )  0.11s user 0.04s system 84% cpu 0.185 total
( swift watcher.swift get; )  0.12s user 0.04s system 85% cpu 0.183 total
( swift watcher.swift get; )  0.12s user 0.04s system 85% cpu 0.184 total
( swift watcher.swift get; )  0.12s user 0.04s system 85% cpu 0.183 total

difference 1: +0.161
difference 2: +0.158
difference 3: +0.151
difference 4: +0.156
```

**Comment by vimpostor** [comment]
Very interesting, but I think that 20 milliseconds is still a bit slow (though definitely a lot better). I wonder whether compiling with `-O` improves the situation. I would test this myself, but I don't have a MacOS system to test with...

**Comment by ghost** [comment]
compiled with `swiftc -O`
```
( ./watcher-optimized get; )  0.01s user 0.01s system 49% cpu 0.030 total
( ./watcher-optimized get; )  0.01s user 0.01s system 55% cpu 0.027 total
( ./watcher-optimized get; )  0.01s user 0.01s system 52% cpu 0.028 total
( ./watcher-optimized get; )  0.01s user 0.01s system 54% cpu 0.028 total
```

`swiftc watcher.swift` - `swiftc -O watcher.swift -o watcher-optimized`
```
difference 1: +0.006
difference 2: +0.002
difference 3: -0.005
difference 4: +0.001
```

binary size
```
❯ stat '-f%z %N' watcher
66148 watcher
❯ stat '-f%z %N' watcher-optimized
68548 watcher-optimized
```

Looks like not much of an improvement. Binary size got slightly bigger though.

**Comment by vimpostor** [comment]
OK thanks for testing, can you see if latest `master` fixes the problem? Now only the very first start after installation should be slow, and then the compiled version will be used.

Also maybe you can help with some technical details:

- Will `swiftc` always output the binary in the directory of the source file, even when the current PWD is another directory?
- Is it safe to assume that `swiftc` is installed, when `swift` is installed?

**Comment by ghost** [comment]
Unfortunately, vimpostor/vim-lumen@a0c55db did broke the functionality. I fixed the problems on my fork based on your commit, sending pull request now.

**Comment by vimpostor** [comment]
> I fixed the problems on my fork based on your commit, sending pull request now.

Awesome, thanks!
